// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ListedCompany.Models
{
    public partial class CompanyData
    {
        /// <summary>
        /// 公司代號
        /// </summary>
        public string CompanyId { get; set; }
        /// <summary>
        /// 公司名稱
        /// </summary>
        public string CompanyName { get; set; }
        /// <summary>
        /// 產業別
        /// </summary>
        public string Industry { get; set; }
    }
}