// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ListedCompany.Models
{
    public partial class db_aaa9ad_project20240703Context : DbContext
    {
        public db_aaa9ad_project20240703Context()
        {
        }

        public db_aaa9ad_project20240703Context(DbContextOptions<db_aaa9ad_project20240703Context> options)
            : base(options)
        {
        }

        public virtual DbSet<CompanyData> CompanyData { get; set; }
        public virtual DbSet<MonRevenue> MonRevenue { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CompanyData>(entity =>
            {
                entity.HasKey(e => e.CompanyId)
                    .HasName("PK__LISTED_C__2D971C4CE7FA862B");

                entity.ToTable("COMPANY_DATA");

                entity.Property(e => e.CompanyId)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("CompanyID")
                    .HasComment("公司代號");

                entity.Property(e => e.CompanyName)
                    .HasMaxLength(50)
                    .HasComment("公司名稱");

                entity.Property(e => e.Industry)
                    .HasMaxLength(50)
                    .HasComment("產業別");
            });

            modelBuilder.Entity<MonRevenue>(entity =>
            {
                entity.HasKey(e => new { e.CompanyId, e.ReportDate, e.DataYearMonth })
                    .HasName("PK__MON_REVE__0D8C5E70E411C5A1");

                entity.ToTable("MON_REVENUE");

                entity.Property(e => e.CompanyId)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("CompanyID")
                    .HasComment("公司代號");

                entity.Property(e => e.ReportDate)
                    .HasColumnType("date")
                    .HasComment("出表日期");

                entity.Property(e => e.DataYearMonth)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasComment("資料年月");

                entity.Property(e => e.CumulativeRevenueChangePreviousPeriod)
                    .HasColumnType("decimal(18, 7)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("累計營業收入-前期比較增減(%)");

                entity.Property(e => e.CumulativeRevenueCurrentMonth)
                    .HasColumnType("decimal(18, 2)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("累計營業收入-當月累計營收");

                entity.Property(e => e.CumulativeRevenueLastYear)
                    .HasColumnType("decimal(18, 2)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("累計營業收入-去年累計營收");

                entity.Property(e => e.Notes)
                    .HasMaxLength(255)
                    .HasDefaultValueSql("('-')")
                    .HasComment("備註");

                entity.Property(e => e.RevenueChangePreviousMonth)
                    .HasColumnType("decimal(18, 2)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("營業收入-上月比較增減(%)");

                entity.Property(e => e.RevenueChangeSameMonthLastYear)
                    .HasColumnType("decimal(18, 7)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("營業收入-去年同月增減(%)");

                entity.Property(e => e.RevenueCurrentMonth)
                    .HasColumnType("decimal(18, 2)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("營業收入-當月營收");

                entity.Property(e => e.RevenuePreviousMonth)
                    .HasColumnType("decimal(18, 2)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("營業收入-上月營收");

                entity.Property(e => e.RevenueSameMonthLastYear)
                    .HasColumnType("decimal(18, 2)")
                    .HasDefaultValueSql("((0))")
                    .HasComment("營業收入-去年當月營收");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}